version: '3'

services:
  db:
    container_name: container_nest-07-ecommerce_part4
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_NAME: ${DATABASE_NAME} # Este nombre tiene que coincidir con el del nombre del proyecto porque es el nombre que levanta en docker
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data